### ISSUE TITLE
After updating qgis the gis4wrf doesn't want to load:  'numpy.ndarray' has no attribute 'array_function'

### ISSUE THREAD

**Issue by mostamndi** [GIS4WRF/gis4wrf#111]
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 24, in classFactory
    from gis4wrf.plugin.plugin import QGISPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 17, in 
    from gis4wrf.core import (
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/__init__.py", line 6, in 
    from gis4wrf.core.downloaders.dist import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/downloaders/dist.py", line 10, in 
    from gis4wrf.core.util import export, remove_dir
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/util.py", line 14, in 
    import numpy as np
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in 
    from . import core
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 59, in 
    from . import numeric
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 3093, in 
    from . import fromnumeric
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 17, in 
    from . import _methods
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/suleiman/.local/lib/python3.6/site-packages/numpy/core/_methods.py", line 158, in 
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.4.4-Madeira Madeira, f6ddc62 

Python Path:
/usr/share/qgis/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/suleiman/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/gis4wrf/python36/local/lib/python3.6/dist-packages
/home/suleiman/.local/share/gis4wrf/python36/lib/python3/dist-packages
/home/suleiman/.local/share/gis4wrf/python36/lib/python3.6/dist-packages

**Comment by mostamndi** [comment]
The problem was solved after reinstalling numpy 
pip3 install -U numpy 

Best regards,
Suleiman
