### ISSUE TITLE
Error after updating Gis4WRF 

### ISSUE THREAD

**Issue by mostamndi** [GIS4WRF/gis4wrf#134]
An error has occurred while executing Python code: 

AttributeError: module 'gis4wrf' has no attribute 'plugin' 
Traceback (most recent call last):
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_view.py", line 231, in on_dataset_selected
    self.init_time_selector()
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_view.py", line 176, in init_time_selector
    self.on_time_selected(selected_time)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_view.py", line 262, in on_time_selected
    self.select_time_band_in_variable_layers()
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_view.py", line 305, in select_time_band_in_variable_layers
    layers = gis4wrf.plugin.geo.get_raster_layers_in_group(dataset.name)
AttributeError: module 'gis4wrf' has no attribute 'plugin'

Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.6.2-Noosa Noosa, 656500e 

Python Path:
/usr/share/qgis/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/suleiman/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/gis4wrf/python36/local/lib/python3.6/dist-packages
/home/suleiman/.local/share/gis4wrf/python36/lib/python3/dist-packages
/home/suleiman/.local/share/gis4wrf/python36/lib/python3.6/dist-packages
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/suleiman/.local/lib/python3.6/site-packages/IPython/extensions
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/../pyqtgraph-0.10.0-py2.py3-none-any.whl

**Comment by mostamndi** [comment]
[SOLVED]
After updating of QGIS to version 3.62 the problem is gone!

**Comment by dmey** [comment]
Thanks
