### ISSUE TITLE
Python error ds083.3

### ISSUE THREAD

**Issue by Gianfoke** [GIS4WRF/gis4wrf#147]
Hello

I'm new of GIS4WRF. I'm exactly following the tutorial about heat wave in Amsterdam but when I try to download meteorological dataset ds083.3 I find this error message:

2019-10-04T19:22:44     WARNING    Traceback (most recent call last):
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_met.py", line 129, in on_dataset_changed
              self.products = get_met_products(dataset_name, auth)
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\core\downloaders\met.py", line 28, in get_met_products
              response.raise_for_status()
              File "C:\Program Files\QGIS3~1.8\apps\Python37\lib\site-packages\requests\models.py", line 939, in raise_for_status
              raise HTTPError(http_error_msg, response=self)
             requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://rda.ucar.edu/apps/metadata/ds083.3

Someone has already experimented a similar error in the script?

Thank you

**Comment by letmaik** [comment]
It says unauthorized, are you sure your user/password details for RDA are correct in the settings?
