### ISSUE TITLE
Error opening GIS4WRF

### ISSUE THREAD

**Issue by sampr7** [GIS4WRF/gis4wrf#174]
**Describe the bug**
All of a sudden GIS4WRF stopped working and showing a python error when clicking on the icon.

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - QGIS: 3.14

**Error message**

WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

Python error

2020-07-10T21:07:31     WARNING    Traceback (most recent call last):
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 85, in show_dock
              self.dock_widget = MainDock(self.iface, self.dock_widget)
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/dock.py", line 22, in __init__
              self.simulation_tab = SimulationTab(iface)
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/tab_simulation.py", line 53, in __init__
              self.set_project_in_tabs()
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/tab_simulation.py", line 74, in set_project_in_tabs
              self.datasets_tab.project = project
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_datasets.py", line 71, in project
              self.populate_met_data_tree()
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_datasets.py", line 660, in populate_met_data_tree
              folder_meta, file_metas = read_grib_folder_metadata(time_range_folder)
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/grib_metadata.py", line 32, in read_grib_folder_metadata
              return read_grib_files_metadata(paths)
              File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/grib_metadata.py", line 50, in read_grib_files_metadata
              assert not set(meta.times).intersection(times)
             AssertionError

**Comment by sampr7** [comment]
Fixed by deleting met folder.
