### ISSUE TITLE
syntax error in classFactory (?)

### ISSUE THREAD

**Issue by greytear** [GIS4WRF/gis4wrf#21]
After installing all dependencies, I get an error while trying to load the plugin:

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 24, in classFactory
    from gis4wrf.plugin.plugin import QGISPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 14, in 
    from gis4wrf.core import (
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/__init__.py", line 8, in 
    from gis4wrf.core.downloaders.met import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/downloaders/met.py", line 22
    response = requests_retry_session().get(f'https://rda.ucar.edu/apps/metadata/{dataset_name}', auth=auth)
                                                                                               ^
SyntaxError: invalid syntax

Versão do Python: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] 
Versão do QGIS: 3.2.0-Bonn Bonn, bc43194 

Diretório do Python:
/usr/share/qgis/python
/home/luis/.local/share/QGIS/QGIS3/profiles/default/python
/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/luis/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/luis/.local/share/QGIS/QGIS3/profiles/default/python
/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Beeline/libs
/home/luis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
/home/luis/.local/share/gis4wrf/python/local/lib/python3.5/dist-packages
/home/luis/.local/share/gis4wrf/python/lib/python3/dist-packages
/home/luis/.local/share/gis4wrf/python/lib/python3.5/dist-packages

**Comment by dmey** [comment]
We only support Ubuntu (17.x, 18.x) -- see [this](https://github.com/GIS4WRF/gis4wrf/blob/master/INSTALL.md#ubuntu). What system are you using?

**Comment by greytear** [comment]
Using debian 9.4 with qgis 3.2.0

**Comment by dmey** [comment]
We only support Ubuntu (17.x, 18.x) and Python 3.6 for the reasons explained [here](https://github.com/GIS4WRF/gis4wrf/issues/16#issuecomment-401564951). Debian 9.4 installed Python 3.5.
