### ISSUE TITLE
Installing Python packages fails on QGIS 3.20 on Windows

### ISSUE THREAD

**Issue by letmaik** [GIS4WRF/gis4wrf#214]
```
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\...\AppData\Local\gis4wrf\python39 as module search pathAdded C:\Users\...\AppData\Local\gis4wrf\python39\lib\site-packages as module search pathPackage directory: C:\Users\...\AppData\Local\gis4wrf\python39C:\Program Files\QGIS 3.20.0\bin\python-qgis.bat -m pip install --prefix C:\Users\...\AppData\Local\gis4wrf\python39 f90nml==1.0.2WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/ Could not fetch URL https://pypi.org/simple/f90nml/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/f90nml/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping ERROR: Could not find a version that satisfies the requirement f90nml==1.0.2 (from versions: none) ERROR: No matching distribution found for f90nml==1.0.2 WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 
Traceback (most recent call last):
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 205, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 234, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['C:\\Program Files\\QGIS 3.20.0\\bin\\python-qgis.bat', '-m', 'pip', 'install', '--prefix', 'C:\\Users\\...\\AppData\\Local\\gis4wrf\\python39', 'f90nml==1.0.2']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\...\AppData\Local\gis4wrf\python39 as module search pathAdded C:\Users\...\AppData\Local\gis4wrf\python39\lib\site-packages as module search pathPackage directory: C:\Users\...\AppData\Local\gis4wrf\python39C:\Program Files\QGIS 3.20.0\bin\python-qgis.bat -m pip install --prefix C:\Users\...\AppData\Local\gis4wrf\python39 f90nml==1.0.2WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
Could not fetch URL https://pypi.org/simple/f90nml/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/f90nml/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement f90nml==1.0.2 (from versions: none)
ERROR: No matching distribution found for f90nml==1.0.2
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping



Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 

Python Path:
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.20.0\bin
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\...\AppData\Local\gis4wrf\python39
C:\Users\...\AppData\Local\gis4wrf\python39\lib\site-packages
```

**Comment by letmaik** [comment]
Upstream issue... https://github.com/qgis/QGIS/issues/44185
