### ISSUE TITLE
Installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by TeamGhana** [GIS4WRF/gis4wrf#233]
**Describe the bug**
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'f90nml' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 24, in classFactory
    from gis4wrf.plugin.plugin import QGISPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 17, in 
    from gis4wrf.core import (
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/__init__.py", line 14, in 
    from gis4wrf.core.readers.namelist import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/namelist.py", line 10, in 
    import f90nml
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'f90nml'

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0] 
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python Path:
/usr/share/qgis/python
/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python
/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/agbeli/.local/share/QGIS/QGIS3/profiles/default/python
/home/agbeli/.local/share/gis4wrf/python38/local/lib/python3.8/dist-packages
/home/agbeli/.local/share/gis4wrf/python38/lib/python3/dist-packages
/home/agbeli/.local/share/gis4wrf/python38/lib/python3.8/dist-packages
/home/agbeli/gisdata/QGreenland_v1.0.2

**To Reproduce**
1. Go to 'Open QGIS in Ubuntu, install plugins'
2. Click on 'GIS4WRF'
4. See error above

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - QGIS: [e.g. 3.10.0]

**Additional context**
I am running Ubuntu 20.04 on an LG Gram 17.

**Comment by letmaik** [comment]
The installation notes for Ubuntu haven't been updated in a while: https://gis4wrf.github.io/installation/#ubuntu

Can you run `pip3 install --user f90nml netCDF4` and report back? Make sure you don't run this in any virtual environment of Python (like conda or virtualenv etc.).

**Comment by TeamGhana** [comment]
Thank you. I got it installed successfully on an upgraded ubuntu 21.10.
