### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'asscalar' 

### ISSUE THREAD

**Issue by bakamotokatas** [GIS4WRF/gis4wrf#240]
Hello, I came up with a new issue.

**Describe the bug**
GIS4WRF doesn't load since the last distribution update.

```
AttributeError: module 'numpy' has no attribute 'asscalar' 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 24, in classFactory
    from gis4wrf.plugin.plugin import QGISPlugin
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 17, in 
    from gis4wrf.core import (
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/__init__.py", line 27, in 
    from gis4wrf.core.transforms.wrf_netcdf_to_gdal import *
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/transforms/wrf_netcdf_to_gdal.py", line 18, in 
    import wrf
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/wrf/__init__.py", line 16, in 
    from . import api
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/wrf/api.py", line 6, in 
    from .constants import (ALL_TIMES, Constants, ConversionFactors,
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/wrf/constants.py", line 17, in 
    setattr(Constants, key.upper(), np.asscalar(val))
  File "/usr/lib/python3.10/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start QGIS

**Expected behaviour**
GIS4WRF plugin should be loaded, without problem

**Screenshots**
![image](https://user-images.githubusercontent.com/22841746/179955738-7288d8b3-f1e5-4bb3-b8bd-952898452268.png)

**System Information (please complete the following information):**
OS: Manjaro 21.3.4
QGIS: 3.24.3-Tisler
GIS4WRF version 0.14.7
Qt version 5.15.5
Python version 3.10.5
GDAL/OGR version 3.4.3
NumPy version 1.23.0
PROJ version 8.2.0
EPSG Registry database version v10.038 (2021-10-21)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.39.1
PDAL version 2.4.2
SpatiaLite version 5.0.1
QWT version 6.2.0
QScintilla2 version 2.13.3

**Comment by bakamotokatas** [comment]
Hello, the problem is caused by wrf-python. Updating wrf-python to 1.3.2.6 or higher solves the problem.
