### ISSUE TITLE
Error in Installation, Ubuntu 22.04, Python 3.10.6, QGIS 3.22.11

### ISSUE THREAD

**Issue by mcassiani** [GIS4WRF/gis4wrf#243]
**Describe the bug**

Hi, first of all let me thank you for developing this very useful  tool.
Installing it on Ubuntu 22.04 I got the message below from the python scripts.
In the system Python 3.10 and pip are installed. 
Best Regards, 
Massimo.

RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/mc/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages as module search pathAdded /home/mc/.local/share/gis4wrf/python310/lib/python3/site-packages as module search pathAdded /home/mc/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search pathPackage directory: /home/mc/.local/share/gis4wrf/python310/usr/local/bin/python3 -m pip install --prefix /home/mc/.local/share/gis4wrf/python310 f90nml==1.0.2 netCDF4==1.* cftime==1.* 
Traceback (most recent call last):
  File "/home/mc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "/home/mc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 237, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "/home/mc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 251, in run_subprocess
    process = subprocess.Popen(args,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/mc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "/home/mc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added /home/mc/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages as module search pathAdded /home/mc/.local/share/gis4wrf/python310/lib/python3/site-packages as module search pathAdded /home/mc/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search pathPackage directory: /home/mc/.local/share/gis4wrf/python310/usr/local/bin/python3 -m pip install --prefix /home/mc/.local/share/gis4wrf/python310 f90nml==1.0.2 netCDF4==1.* cftime==1.*

Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
QGIS version: 3.22.11-Białowieża Białowieża, 106d33d759 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - QGIS: [e.g. 3.10.0]

**Additional context**

**Comment by mcassiani** [comment]
I installed the packages with
  pip3 install --user f90nml pyyaml netCDF4 wrf-python
and the error above is now corrected. 
best regards
