### ISSUE TITLE
QGIS 3.30.2 and GIS4WRF 0.14.7 still have bugs that were previously fixed

### ISSUE THREAD

**Issue by Qianjk818** [GIS4WRF/gis4wrf#252]
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\QJK\AppData\Local\gis4wrf\python39 as module search pathAdded C:\Users\QJK\AppData\Local\gis4wrf\python39\lib\site-packages as module search path 
Traceback (most recent call last):
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:\Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 164, in bootstrap
    pkg_resources.get_distribution('{}>={}'.format(dep.name, dep.min))
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 524, in get_distribution
    dist = Requirement.parse(dist)
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 3211, in parse
    (req,) = parse_requirements(s)
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 3170, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Program Files/QGIS 3.30.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:\Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\QJK\AppData\Local\gis4wrf\python39 as module search pathAdded C:\Users\QJK\AppData\Local\gis4wrf\python39\lib\site-packages as module search path

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Python Path:
C:\Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geohey_toolbox
E:/Program Files/QGIS 3.30.2/apps/qgis/./python
C:/Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
E:/Program Files/QGIS 3.30.2/apps/qgis/./python/plugins
E:\Program Files\QGIS 3.30.2\apps\grass\grass82\etc\python
C:\Users\QJK\Documents
E:\Program Files\QGIS 3.30.2\bin\python39.zip
E:\Program Files\QGIS 3.30.2\apps\Python39\DLLs
E:\Program Files\QGIS 3.30.2\apps\Python39\lib
E:\Program Files\QGIS 3.30.2\bin
E:\Program Files\QGIS 3.30.2\apps\Python39
E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages
E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\win32
E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\win32\lib
E:\Program Files\QGIS 3.30.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/QJK/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\QJK\AppData\Local\gis4wrf\python39
C:\Users\QJK\AppData\Local\gis4wrf\python39\lib\site-packages

**Comment by jokulsarlon** [comment]
the same error in QGIS 3.34.2 and QGIS 3.28.12

**Comment by Shaivishukla** [comment]
@Qianjk818 , @smlie2020 How you sorted this error. I am also facing the same error. It will be helpful if you share it.

**Comment by Qianjk818** [comment]
> @Qianjk818 , @smlie2020 How you sorted this error. I am also facing the same error. It will be helpful if you share it.

I didn't find a good solution, but changing the version worked. I'm not entirely sure of the reason for the problem, so I'm not sure if a higher or lower version is needed, but after reinstalling several times, the issue disappeared, so just keep trying.

**Comment by Shaivishukla** [comment]
@Qianjk818 Thankyou for your reply. Can you please tell me which version you are using.

**Comment by Qianjk818** [comment]
> @Qianjk818 Thankyou for your reply. Can you please tell me which version you are using.
3.28.0

**Comment by Shaivishukla** [comment]
@Qianjk818 Thankyou

**Comment by bakamotokatas** [comment]
https://github.com/GIS4WRF/gis4wrf/issues/259#issuecomment-2082131588

@smlie2020 @Qianjk818 @Shaivishukla
