### ISSUE TITLE
Error loading GIS4WRF

### ISSUE THREAD

**Issue by fipoucat** [GIS4WRF/gis4wrf#254]
I can't load GIS4WRF on ubuntu 22.04 and QGIS 3.22 with its error message

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] 
QGIS version: 3.22.16-Białowieża Białowieża, exported 

Python Path:
/usr/share/qgis/python
/home/sarr/.local/share/QGIS/QGIS3/profiles/default/python
/home/sarr/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/sarr/.local/lib/python3.10/site-packages
/media/sarr/DATA/work/get-station-data
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/sarr/.local/share/QGIS/QGIS3/profiles/default/python
/home/sarr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/sarr/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/sarr/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages
/home/sarr/.local/share/gis4wrf/python310/lib/python3/site-packages
/home/sarr/.local/share/gis4wrf/python310/lib/python3.10/site-packages

**Comment by HathewayWill** [comment]
Getting similar issue too:
```

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/workhorse/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search pathPackage directory: /home/workhorse/.local/share/gis4wrf/python310/usr/local/bin/python3 -m pip install --prefix /home/workhorse/.local/share/gis4wrf/python310 f90nml==1.0.2 netCDF4==1.* cftime==1.* 
Traceback (most recent call last):
  File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 237, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 251, in run_subprocess
    process = subprocess.Popen(args,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added /home/workhorse/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search pathPackage directory: /home/workhorse/.local/share/gis4wrf/python310/usr/local/bin/python3 -m pip install --prefix /home/workhorse/.local/share/gis4wrf/python310 f90nml==1.0.2 netCDF4==1.* cftime==1.*


Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] 
QGIS version: 3.28.8-Firenze Firenze, 5ac45272b5 

Python Path:
/usr/share/qgis/python
/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python
/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/workhorse/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python
/home/workhorse/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages
/home/workhorse/.local/share/gis4wrf/python310/lib/python3/site-packages
/home/workhorse/.local/share/gis4wrf/python310/lib/python3.10/site-packages
```

**Comment by HathewayWill** [comment]
> Getting similar issue too:
> 
> ```
> 
> Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 
> 
> RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/workhorse/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search pathPackage directory: /home/workhorse/.local/share/gis4wrf/python310/usr/local/bin/python3 -m pip install --prefix /home/workhorse/.local/share/gis4wrf/python310 f90nml==1.0.2 netCDF4==1.* cftime==1.* 
> Traceback (most recent call last):
>   File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 39, in bootstrap_with_ui
>     for msg_type, msg_val in bootstrap():
>   File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 237, in bootstrap
>     for line in run_subprocess(args, LOG_PATH):
>   File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 251, in run_subprocess
>     process = subprocess.Popen(args,
>   File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python3'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
>     bootstrap_with_ui(iface)
>   File "/home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
>     raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
> RuntimeError: GIS4WRF: Error installing Python packages
> Log:
> Added /home/workhorse/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3/site-packages as module search pathAdded /home/workhorse/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search pathPackage directory: /home/workhorse/.local/share/gis4wrf/python310/usr/local/bin/python3 -m pip install --prefix /home/workhorse/.local/share/gis4wrf/python310 f90nml==1.0.2 netCDF4==1.* cftime==1.*
> 
> 
> Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] 
> QGIS version: 3.28.8-Firenze Firenze, 5ac45272b5 
> 
> Python Path:
> /usr/share/qgis/python
> /home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python
> /home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python310.zip
> /usr/lib/python3.10
> /usr/lib/python3.10/lib-dynload
> /home/workhorse/.local/lib/python3.10/site-packages
> /usr/local/lib/python3.10/dist-packages
> /usr/lib/python3/dist-packages
> /home/workhorse/.local/share/QGIS/QGIS3/profiles/default/python
> /home/workhorse/.local/share/gis4wrf/python310/local/lib/python3.10/site-packages
> /home/workhorse/.local/share/gis4wrf/python310/lib/python3/site-packages
> /home/workhorse/.local/share/gis4wrf/python310/lib/python3.10/site-packages
> ```

```
echo $PASSWD | sudo -S sudo apt install gnupg software-properties-common

echo $PASSWD | sudo -S sudo mkdir -m755 -p /etc/apt/keyrings  # not needed since apt version 2.4.0 like Debian 12 and Ubuntu 22 or newer

echo $PASSWD | sudo -S sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg

echo "Types: deb deb-src
URIs: https://qgis.org/ubuntu-ltr
Suites: jammy
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg" | sudo tee /etc/apt/sources.list.d/qgis.sources

#echo $PASSWD | sudo -S sudo ln -sf /usr/bin/python3 /usr/local/bin/python3

/usr/local/bin/python3 -m pip install f90nml netCDF4

echo $PASSWD | sudo -S sudo apt update -y

echo $PASSWD | sudo -S sudo apt install qgis qgis-plugin-grass -y

echo $PASSWD | sudo -S sudo apt update -y

echo $PASSWD | sudo -S sudo apt upgrade -y
```

tried this and it makes qgis unstable and crashes

**Comment by HathewayWill** [comment]
@dmey any ideas?

**Comment by AbdBaten** [comment]
I have installed the latest version of QGIS (3.2 LIMA) in ubuntu 22.04, but whenever tried to install gis4wrf, the error message "Error installing Python packages" shown. Will you please help to solve the prob?
