### ISSUE TITLE
GIS4WRF installation Error

### ISSUE THREAD

**Issue by mostamndi** [GIS4WRF/gis4wrf#259]
I tried to install Gis4WRF on my Ubuntu 22.04, QGIS 3.36 but got the following Error: 

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/suleiman/.local/share/gis4wrf/python312/lib/python3.12/site-packages as module search path 
Traceback (most recent call last):
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 164, in bootstrap
    pkg_resources.get_distribution('{}>={}'.format(dep.name, dep.min))
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/__init__.py", line 495, in get_distribution
    dist = Requirement.parse(dist)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3176, in parse
    (req,) = parse_requirements(s)
    ^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suleiman/miniconda3/envs/qgis/share/qgis/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added /home/suleiman/.local/share/gis4wrf/python312/lib/python3.12/site-packages as module search path

Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 21:10:00) [GCC 12.3.0] 
QGIS version: 3.36.1-Maidenhead Maidenhead, exported 

Python Path:
/home/suleiman/miniconda3/envs/qgis/share/qgis/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/suleiman/miniconda3/envs/qgis/share/qgis/python/plugins
/home/suleiman/miniconda3/envs/qgis/share/qgis/python/plugins
/home/suleiman/miniconda3/envs/qgis/share/qgis/python
/home/suleiman/apps/mars/lib
/home/suleiman
/home/suleiman/miniconda3/envs/qgis/lib/python312.zip
/home/suleiman/miniconda3/envs/qgis/lib/python3.12
/home/suleiman/miniconda3/envs/qgis/lib/python3.12/lib-dynload
/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/gis4wrf/python312/lib/python3.12/site-packages

Could you please help me how to solve this? 

Thanks. 

Suleiman

**Comment by mostamndi** [comment]
after restarting QGis 

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/suleiman/.local/share/gis4wrf/python312/lib/python3.12/site-packages as module search path 
Traceback (most recent call last):
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 164, in bootstrap
    pkg_resources.get_distribution('{}>={}'.format(dep.name, dep.min))
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/__init__.py", line 495, in get_distribution
    dist = Requirement.parse(dist)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3176, in parse
    (req,) = parse_requirements(s)
    ^^^^^^
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suleiman/miniconda3/envs/qgis/share/qgis/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added /home/suleiman/.local/share/gis4wrf/python312/lib/python3.12/site-packages as module search path


Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 21:10:00) [GCC 12.3.0] 
QGIS version: 3.36.1-Maidenhead Maidenhead, exported 

Python Path:
/home/suleiman/miniconda3/envs/qgis/share/qgis/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/suleiman/miniconda3/envs/qgis/share/qgis/python/plugins
/home/suleiman/miniconda3/envs/qgis/share/qgis/python/plugins
/home/suleiman/miniconda3/envs/qgis/share/qgis/python
/home/suleiman/apps/mars/lib
/home/suleiman/.local/share/gis4wrf/python312/lib/python3.12/site-packages
/home/suleiman/miniconda3/envs/qgis/lib/python312.zip
/home/suleiman/miniconda3/envs/qgis/lib/python3.12
/home/suleiman/miniconda3/envs/qgis/lib/python3.12/lib-dynload
/home/suleiman/miniconda3/envs/qgis/lib/python3.12/site-packages
/home/suleiman/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by Shaivishukla** [comment]
@mostamndi  How you sorted this error. I am also facing the same error. It will be helpful if you share it.

**Comment by bakamotokatas** [comment]
Download the repository as zip or clone. Then there is build.py in the folder, run it as 'python3 build.py' and the gis4wrf.zip file will be created. After that, open QGIS -> Plugins -> Manage and Install Plugins -> Install from ZIP -> find your gis4wrf.zip file -> Install Plugin. As a result, you will be able to install successfully.

@mostamndi

**Comment by jokulsarlon** [comment]
> Download the repository as zip or clone. Then there is build.py in the folder, run it as 'python3 build.py' and the gis4wrf.zip file will be created. After that, open QGIS -> Plugins -> Manage and Install Plugins -> Install from ZIP -> find your gis4wrf.zip file -> Install Plugin. As a result, you will be able to install successfully.
> 
> @mostamndi

I downloaded build.py file and tried to run it with python as well, but it doesn't seem to work at all, can you be more detailed?

**Comment by smlie2020** [comment]
> Download the repository as zip or clone. Then there is build.py in the folder, run it as 'python3 build.py' and the gis4wrf.zip file will be created. After that, open QGIS -> Plugins -> Manage and Install Plugins -> Install from ZIP -> find your gis4wrf.zip file -> Install Plugin. As a result, you will be able to install successfully.
> 
> @mostamndi

build.py there are some problems with the code, after the modification, it works normally, thank you very much。
`# -*- coding: utf-8 -*-
# GIS4WRF (https://doi.org/10.5281/zenodo.1288569)
# Copyright (c) 2018 D. Meyer and M. Riechert. Licensed under MIT.

import os
import sys
import platform
import subprocess
import glob
from fnmatch import fnmatch
import zipfile
import shutil
import json

import PyQt5.pyrcc_main as pyrcc
import yaml

PKG_NAME = 'gis4wrf'

THIS_DIR = os.path.abspath(os.path.dirname(__file__))
PKG_DIR = os.path.join(THIS_DIR, PKG_NAME)
ZIP_FILE = PKG_DIR + '.zip'

# All entries will be interpreted with wildcards around them
ZIP_EXCLUDES = [
    '__pycache__',
    '.gif',
    '.yml'
]

# Create QT resources file

QT_RESOURCES_DIR = os.path.join(PKG_DIR, 'plugin', 'resources')
QT_RESOURCES = glob.glob(os.path.join(QT_RESOURCES_DIR, '*.qrc'))
PYQT_RESOURCE_FILE = os.path.join(QT_RESOURCES_DIR, 'resources.py')

if not pyrcc.processResourceFile(QT_RESOURCES, PYQT_RESOURCE_FILE, listFiles=False):
    print('Error creating PyQT resources file', file=sys.stderr)
    sys.exit(1)

# Convert YAML to JSON

YAML_DIR = os.path.join(PKG_DIR, 'core', 'readers', 'nml_schemas')
YAML_PATHS = glob.glob(os.path.join(YAML_DIR, '*.yml'))
JSON_PATHS = [os.path.splitext(yaml_path)[0] + '.json' for yaml_path in YAML_PATHS]

for yaml_path, json_path in zip(YAML_PATHS, JSON_PATHS):
    with open(yaml_path, 'r', encoding='utf-8') as yaml_file:
        with open(json_path, 'w', encoding='utf-8') as json_file:
            json.dump(yaml.safe_load(yaml_file), json_file, indent=1, ensure_ascii=False)

# Symlink plugin into QGIS plugins folder

if platform.system() == 'Windows' or platform.system() == 'Darwin':
    PLATFORM = platform.system()
    HOME = os.path.expanduser('~')
    if PLATFORM == 'Windows':
        QGIS_PLUGINS_DIR = os.path.join(HOME, 'AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins')
    elif PLATFORM == 'Darwin':
        QGIS_PLUGINS_DIR = os.path.join(HOME, 'Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins')
    QGIS_PLUGIN_DIR = os.path.join(QGIS_PLUGINS_DIR, PKG_NAME)

    if not os.path.exists(os.path.dirname(QGIS_PLUGINS_DIR)):
        print('Could not find QGIS3 user profile folder, not creating symlink for plugin', file=sys.stderr)
    elif os.path.exists(QGIS_PLUGIN_DIR):
        print('Folder {} exists, not creating symlink'.format(QGIS_PLUGIN_DIR))
    else:
        # QGIS only creates the /plugins folder after installing the first plugin
        if not os.path.exists(QGIS_PLUGINS_DIR):
            os.mkdir(QGIS_PLUGINS_DIR)
        try:
            if PLATFORM == 'Windows':
                subprocess.check_output(['mklink', '/j', QGIS_PLUGIN_DIR, PKG_DIR], shell=True)
            elif PLATFORM == 'Darwin':
                os.symlink(PKG_DIR, QGIS_PLUGIN_DIR)
        except subprocess.CalledProcessError as err:
            print('Error creating symlink for plugin:')
            print(err.output, file=sys.stderr)

# Copy CHANGELOG.txt, ATTRIBUTION.txt, and LICENSE.txt into gis4wrf plugin directory
print('Copying CHANGELOG.txt to the package directory: '+ PKG_DIR)
shutil.copy(os.path.join(THIS_DIR,'CHANGELOG.txt' ), os.path.join(PKG_DIR,'CHANGELOG.txt'))
print('Copying ATTRIBUTION.txt to the package directory: '+ PKG_DIR)
shutil.copy(os.path.join(THIS_DIR,'ATTRIBUTION.txt' ), os.path.join(PKG_DIR,'ATTRIBUTION.txt'))
print('Copying LICENSE.txt to the package directory: '+ PKG_DIR)
shutil.copy(os.path.join(THIS_DIR,'LICENSE.txt' ), os.path.join(PKG_DIR,'LICENSE.txt'))

# Package into ZIP file
def create_zip(zip_path, folder_path, ignore_patterns):
    print('Creating ZIP archive ' + zip_path)
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk(folder_path):
            for file in files:
                path = os.path.join(root, file)
                archive_path = os.path.relpath(os.path.join(root, file), os.path.join(folder_path, os.pardir))
                if not any(fnmatch(path, '*' + ignore + '*') for ignore in ignore_patterns):
                    print('Adding ' + archive_path)
                    zipf.write(path, archive_path)
                else:
                    print('Ignoring ' + archive_path)
    print('Created ZIP archive ' + zip_path)

create_zip(ZIP_FILE, PKG_DIR, ZIP_EXCLUDES)
`

**Comment by jokulsarlon** [comment]
> Download the repository as zip or clone. Then there is build.py in the folder, run it as 'python3 build.py' and the gis4wrf.zip file will be created. After that, open QGIS -> Plugins -> Manage and Install Plugins -> Install from ZIP -> find your gis4wrf.zip file -> Install Plugin. As a result, you will be able to install successfully.
> 
> @mostamndi

build.py there are some problems with the code, after the modification, it works normally, thank you very much。
[build.zip](https://github.com/GIS4WRF/gis4wrf/files/15160064/build.zip)

**Comment by LreeLenn** [comment]
the new link of basemap from geo.py which should be edited:
https://tiles.stadiamaps.com/tiles/stamen_terrain_background/{z}/{x}/{y}.png

**Comment by bakamotokatas** [comment]
@smlie2020 not just build.py file download whole repo.

**Comment by jokulsarlon** [comment]
> @smlie2020 not just build.py file download whole repo.

yes，It has been installed successfully
