### ISSUE TITLE
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by Shaivishukla** [GIS4WRF/gis4wrf#260]
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\Shaivi Shukla\AppData\Local\gis4wrf\python39 as module search pathAdded C:\Users\Shaivi Shukla\AppData\Local\gis4wrf\python39\lib\site-packages as module search path 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:\Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 164, in bootstrap
    pkg_resources.get_distribution('{}>={}'.format(dep.name, dep.min))
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 524, in get_distribution
    dist = Requirement.parse(dist)
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 3211, in parse
    (req,) = parse_requirements(s)
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 3170, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    netCDF4>=None
           ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:\Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\Shaivi Shukla\AppData\Local\gis4wrf\python39 as module search pathAdded C:\Users\Shaivi Shukla\AppData\Local\gis4wrf\python39\lib\site-packages as module search path

Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.34.5-Prizren Prizren, 4b308492 

Python Path:
C:/PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python
C:/Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.5\apps\grass\grass83\etc\python
C:\WINDOWS\System32
C:\Program Files\QGIS 3.34.5\bin\python39.zip
C:\PROGRA~1\QGIS33~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.34.5\bin
C:\PROGRA~1\QGIS33~1.5\apps\Python39
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Shaivi Shukla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Shaivi Shukla\AppData\Local\gis4wrf\python39
C:\Users\Shaivi Shukla\AppData\Local\gis4wrf\python39\lib\site-packages

Getting this error when trying to install the GIS4WRF plugin.

**Comment by bakamotokatas** [comment]
https://github.com/GIS4WRF/gis4wrf/issues/259#issuecomment-2082131588
