### ISSUE TITLE
QgsSingleSymbolRenderer(): not enough arguments 

### ISSUE THREAD

**Issue by ved-ux** [GIS4WRF/gis4wrf#261]
### _I'm encountering the error below when attempting to import namelist.wps. :-_ 

An error has occurred while executing Python code: 

TypeError: QgsSingleSymbolRenderer(): not enough arguments 
Traceback (most recent call last):
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/tab_simulation.py", line 106, in open_project_from_object
    self.set_project_in_tabs()
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/tab_simulation.py", line 73, in set_project_in_tabs
    self.domain_tab.project = project
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_domains.py", line 230, in project
    self.populate_ui_from_project()
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_domains.py", line 286, in populate_ui_from_project
    self.draw_bbox_and_grids(zoom_out=True)
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_domains.py", line 561, in draw_bbox_and_grids
    update_domain_outline_layers(self.iface.mapCanvas(), project, zoom_out=zoom_out)
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/geo.py", line 75, in update_domain_outline_layers
    renderer = QgsSingleSymbolRenderer(sym)  # Create the renderer with the symbol
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QgsSingleSymbolRenderer(): not enough arguments

Python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:26:14) [GCC 12.2.0] 
QGIS version: 3.28.8-Firenze Firenze, exported 

Python Path:
/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/generate_swmm_inp
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/share/qgis/python
/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python
/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/share/qgis/python/plugins
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/share/qgis/python/plugins
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/share/qgis/python
/home/wrf_hydro_fnl/WRF/WPS-4.5
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/lib/python311.zip
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/lib/python3.11
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/lib/python3.11/lib-dynload
/home/wrf_hydro_fnl/WRF/miniconda3/envs/qgis_stable.3.28.8/lib/python3.11/site-packages
/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python
/home/wrf_hydro_fnl/.local/share/gis4wrf/python311/lib/python3.11/site-packages
/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_linux

**Comment by ved-ux** [comment]
Please suggest the required correction to be done . I am still getting the same error while importing namelist.wps.

An error has occurred while executing Python code: 

TypeError: QgsSingleSymbolRenderer(): not enough arguments 
Traceback (most recent call last):
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/tab_simulation.py", line 106, in open_project_from_object
    self.set_project_in_tabs()
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/tab_simulation.py", line 73, in set_project_in_tabs
    self.domain_tab.project = project
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_domains.py", line 230, in project
    self.populate_ui_from_project()
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_domains.py", line 286, in populate_ui_from_project
    self.draw_bbox_and_grids(zoom_out=True)
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_domains.py", line 561, in draw_bbox_and_grids
    update_domain_outline_layers(self.iface.mapCanvas(), project, zoom_out=zoom_out)
  File "/home/wrf_hydro_fnl/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/geo.py", line 75, in update_domain_outline_layers
    renderer = QgsSingleSymbolRenderer(sym)  # Create the renderer with the symbol
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QgsSingleSymbolRenderer(): not enough arguments


Python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:26:14) [GCC 12.2.0] 
QGIS version: 3.28.8-Firenze Firenze, exported 

 Thank you for your time

**Comment by ved-ux** [comment]
Dear developer 

The details of the operating system are as follows:-

Distributor ID:               Ubuntu
Description:                  Ubuntu 22.04.4 LTS
Release:                         22.04
Codename:                     jammy

Thank you for your time. Please check the error
